"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        """
        s_dict = {}
        for i in s:
            if not s_dict.has_key(i):
                s_dict[i] = 1
            else:
                s_dict[i] += 1
        for j in t:
            if not s_dict.has_key(j):
                return j
            else:
                s_dict[j] -= 1
                if s_dict[j]<0:
                    return j
        """
        """
        res = 0
        for i in s:
            res -= ord(i)
        for j in t:
            res += ord(j)
        return chr(res)
        """
        res = 0
        for i in s:
            res ^= ord(i)
        for j in t:
            res ^= ord(j)
        return chr(res)
                